"""added enum value for exam_action status update

Revision ID: 0336b718eb50
Revises: b1046d48518d
Create Date: 2026-08-12 20:22:25.005146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0336b718eb50'
down_revision: Union[str, Sequence[str], None] = 'b1046d48518d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE examaction ADD VALUE IF NOT EXISTS 'EXAM_STATUS_OVERRIDE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
