"""change audit log action to string

Revision ID: 52cb124c4dbf
Revises: cc91c44339b5
Create Date: 2026-08-13 14:47:52.273153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '52cb124c4dbf'
down_revision: Union[str, Sequence[str], None] = 'cc91c44339b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_audit_logs', 'action',
               existing_type=postgresql.ENUM('CREATED', 'UPDATED', 'DELETED', 'RESET', 'SUBMITTED_FOR_APPROVAL', 'APPROVED', 'REJECTED', 'SCHEDULED', 'RESCHEDULED', 'STARTED', 'PAUSED', 'COMPLETED', 'ITEM_ADDED', 'ITEM_REMOVED', 'SECTION_ADDED', 'SECTION_UPDATED', 'ASSIGNED_TO_STUDENT', 'UNASSIGNED_FROM_STUDENT', 'STUDENT_STARTED', 'STUDENT_SUBMITTED', 'STUDENT_AUTO_SUBMITTED', 'SECTION_REMOVED', 'ASSIGNED_TO_COHORT', 'UNASSIGNED_FROM_COHORT', 'REOPENED', 'SETTINGS_UPDATED', 'exam_status_override', 'EXAM_STATUS_OVERRIDE', 'ARCHIVED', name='examaction'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_audit_logs', 'action',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CREATED', 'UPDATED', 'DELETED', 'RESET', 'SUBMITTED_FOR_APPROVAL', 'APPROVED', 'REJECTED', 'SCHEDULED', 'RESCHEDULED', 'STARTED', 'PAUSED', 'COMPLETED', 'ITEM_ADDED', 'ITEM_REMOVED', 'SECTION_ADDED', 'SECTION_UPDATED', 'ASSIGNED_TO_STUDENT', 'UNASSIGNED_FROM_STUDENT', 'STUDENT_STARTED', 'STUDENT_SUBMITTED', 'STUDENT_AUTO_SUBMITTED', 'SECTION_REMOVED', 'ASSIGNED_TO_COHORT', 'UNASSIGNED_FROM_COHORT', 'REOPENED', 'SETTINGS_UPDATED', 'exam_status_override', 'EXAM_STATUS_OVERRIDE', 'ARCHIVED', name='examaction'),
               existing_nullable=False)
    # ### end Alembic commands ###
