"""add deadline_override to ExamAssignment

Revision ID: 802ed88ef555
Revises: 52cb124c4dbf
Create Date: 2026-08-13 16:42:00.863223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802ed88ef555'
down_revision: Union[str, Sequence[str], None] = '52cb124c4dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_assignments', sa.Column('deadline_override', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_assignments', 'deadline_override')
    # ### end Alembic commands ###
