"""added archived value for exam_status enum

Revision ID: 9ce3554d958d
Revises: 0336b718eb50
Create Date: 2026-08-12 20:52:58.935134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce3554d958d'
down_revision: Union[str, Sequence[str], None] = '0336b718eb50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE examstatus ADD VALUE IF NOT EXISTS 'ARCHIVED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
