"""cbt services

Revision ID: b1046d48518d
Revises: 
Create Date: 2026-08-11 11:28:29.108460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b1046d48518d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'SUBMITTED', 'SCORED', 'RESET', name='attemptstatus'), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_assignment_id'), 'attempts', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_attempts_exam_id'), 'attempts', ['exam_id'], unique=False)
    op.create_index(op.f('ix_attempts_org_id'), 'attempts', ['org_id'], unique=False)
    op.create_index(op.f('ix_attempts_status'), 'attempts', ['status'], unique=False)
    op.create_index(op.f('ix_attempts_student_id'), 'attempts', ['student_id'], unique=False)
    op.create_table('exam_review_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_review_checks_exam_id'), 'exam_review_checks', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_review_checks_teacher_id'), 'exam_review_checks', ['teacher_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('rejected_by', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('pass_mark', sa.Float(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'ACTIVE', 'CLOSED', 'REJECTED', name='examstatus'), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('shuffle_options', sa.Boolean(), nullable=False),
    sa.Column('show_result_immediately', sa.Boolean(), nullable=False),
    sa.Column('allow_review', sa.Boolean(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_org_id'), 'exams', ['org_id'], unique=False)
    op.create_index(op.f('ix_exams_status'), 'exams', ['status'], unique=False)
    op.create_index(op.f('ix_exams_subject_id'), 'exams', ['subject_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='subjectstatus'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.create_index(op.f('ix_subjects_org_id'), 'subjects', ['org_id'], unique=False)
    op.create_table('bulk_upload_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_upload_logs_org_id'), 'bulk_upload_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_bulk_upload_logs_subject_id'), 'bulk_upload_logs', ['subject_id'], unique=False)
    op.create_table('exam_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'STARTED', 'SUBMITTED', 'MISSED', name='assignmentstatus'), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_assignments_cohort_id'), 'exam_assignments', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_exam_assignments_exam_id'), 'exam_assignments', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_assignments_org_id'), 'exam_assignments', ['org_id'], unique=False)
    op.create_index(op.f('ix_exam_assignments_student_id'), 'exam_assignments', ['student_id'], unique=False)
    op.create_table('exam_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'DELETED', 'RESET', 'SUBMITTED_FOR_APPROVAL', 'APPROVED', 'REJECTED', 'SCHEDULED', 'RESCHEDULED', 'STARTED', 'PAUSED', 'COMPLETED', 'ITEM_ADDED', 'ITEM_REMOVED', 'SECTION_ADDED', 'SECTION_UPDATED', 'ASSIGNED_TO_STUDENT', 'UNASSIGNED_FROM_STUDENT', 'STUDENT_STARTED', 'STUDENT_SUBMITTED', 'STUDENT_AUTO_SUBMITTED', 'SECTION_REMOVED', 'ASSIGNED_TO_COHORT', 'UNASSIGNED_FROM_COHORT', 'REOPENED', 'SETTINGS_UPDATED', name='examaction'), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_audit_logs_exam_id'), 'exam_audit_logs', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_audit_logs_org_id'), 'exam_audit_logs', ['org_id'], unique=False)
    op.create_table('exam_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_sections_exam_id'), 'exam_sections', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_sections_org_id'), 'exam_sections', ['org_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('item_type', sa.Enum('MCQ_SINGLE', 'MCQ_MULTI', 'SHORT_ANSWER', 'NUMERIC', 'TRUE_FALSE', name='itemtype'), nullable=False),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('correct_answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('negative_marks', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='itemdifficulty'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='itemstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'EXCEL_UPLOAD', 'AI_GENERATED', 'IMPORTED', name='itemsource'), nullable=False),
    sa.Column('bulk_upload_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_bulk_upload_id'), 'items', ['bulk_upload_id'], unique=False)
    op.create_index(op.f('ix_items_created_by'), 'items', ['created_by'], unique=False)
    op.create_index(op.f('ix_items_difficulty'), 'items', ['difficulty'], unique=False)
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    op.create_index(op.f('ix_items_org_id'), 'items', ['org_id'], unique=False)
    op.create_index(op.f('ix_items_source'), 'items', ['source'], unique=False)
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    op.create_index(op.f('ix_items_subject_id'), 'items', ['subject_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('exam_item_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_awarded', sa.Float(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_attempt_id'), 'responses', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_responses_item_id'), 'responses', ['item_id'], unique=False)
    op.create_index(op.f('ix_responses_org_id'), 'responses', ['org_id'], unique=False)
    op.create_table('subject_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_assignments_assigned_to'), 'subject_assignments', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_subject_assignments_org_id'), 'subject_assignments', ['org_id'], unique=False)
    op.create_index(op.f('ix_subject_assignments_subject_id'), 'subject_assignments', ['subject_id'], unique=False)
    op.create_table('exam_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('negative_marks', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['exam_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_items_exam_id'), 'exam_items', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_items_item_id'), 'exam_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_exam_items_org_id'), 'exam_items', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_items_org_id'), table_name='exam_items')
    op.drop_index(op.f('ix_exam_items_item_id'), table_name='exam_items')
    op.drop_index(op.f('ix_exam_items_exam_id'), table_name='exam_items')
    op.drop_table('exam_items')
    op.drop_index(op.f('ix_subject_assignments_subject_id'), table_name='subject_assignments')
    op.drop_index(op.f('ix_subject_assignments_org_id'), table_name='subject_assignments')
    op.drop_index(op.f('ix_subject_assignments_assigned_to'), table_name='subject_assignments')
    op.drop_table('subject_assignments')
    op.drop_index(op.f('ix_responses_org_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_item_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_attempt_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_items_subject_id'), table_name='items')
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index(op.f('ix_items_source'), table_name='items')
    op.drop_index(op.f('ix_items_org_id'), table_name='items')
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.drop_index(op.f('ix_items_difficulty'), table_name='items')
    op.drop_index(op.f('ix_items_created_by'), table_name='items')
    op.drop_index(op.f('ix_items_bulk_upload_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_exam_sections_org_id'), table_name='exam_sections')
    op.drop_index(op.f('ix_exam_sections_exam_id'), table_name='exam_sections')
    op.drop_table('exam_sections')
    op.drop_index(op.f('ix_exam_audit_logs_org_id'), table_name='exam_audit_logs')
    op.drop_index(op.f('ix_exam_audit_logs_exam_id'), table_name='exam_audit_logs')
    op.drop_table('exam_audit_logs')
    op.drop_index(op.f('ix_exam_assignments_student_id'), table_name='exam_assignments')
    op.drop_index(op.f('ix_exam_assignments_org_id'), table_name='exam_assignments')
    op.drop_index(op.f('ix_exam_assignments_exam_id'), table_name='exam_assignments')
    op.drop_index(op.f('ix_exam_assignments_cohort_id'), table_name='exam_assignments')
    op.drop_table('exam_assignments')
    op.drop_index(op.f('ix_bulk_upload_logs_subject_id'), table_name='bulk_upload_logs')
    op.drop_index(op.f('ix_bulk_upload_logs_org_id'), table_name='bulk_upload_logs')
    op.drop_table('bulk_upload_logs')
    op.drop_index(op.f('ix_subjects_org_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_exams_subject_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_status'), table_name='exams')
    op.drop_index(op.f('ix_exams_org_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_exam_review_checks_teacher_id'), table_name='exam_review_checks')
    op.drop_index(op.f('ix_exam_review_checks_exam_id'), table_name='exam_review_checks')
    op.drop_table('exam_review_checks')
    op.drop_index(op.f('ix_attempts_student_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_status'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_org_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_exam_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_assignment_id'), table_name='attempts')
    op.drop_table('attempts')
    # ### end Alembic commands ###
