"""added violations implementation

Revision ID: c1cc4897b572
Revises: 802ed88ef555
Create Date: 2026-09-06 13:29:24.727691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c1cc4897b572'
down_revision: Union[str, Sequence[str], None] = '802ed88ef555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_violations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('violation_type', sa.Enum('tab_switch', 'fullscreen_exit', 'copy_paste', 'right_click', 'dev_tools_opened', 'multiple_faces_detected', 'no_face_detected', 'window_blur', 'other', name='violationtype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='violationseverity'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_violations_attempt_id'), 'exam_violations', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_exam_violations_exam_id'), 'exam_violations', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_violations_org_id'), 'exam_violations', ['org_id'], unique=False)
    op.create_index(op.f('ix_exam_violations_student_id'), 'exam_violations', ['student_id'], unique=False)
    op.create_index(op.f('ix_exam_violations_violation_type'), 'exam_violations', ['violation_type'], unique=False)
    op.add_column('exams', sa.Column('max_violations', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'max_violations')
    op.drop_index(op.f('ix_exam_violations_violation_type'), table_name='exam_violations')
    op.drop_index(op.f('ix_exam_violations_student_id'), table_name='exam_violations')
    op.drop_index(op.f('ix_exam_violations_org_id'), table_name='exam_violations')
    op.drop_index(op.f('ix_exam_violations_exam_id'), table_name='exam_violations')
    op.drop_index(op.f('ix_exam_violations_attempt_id'), table_name='exam_violations')
    op.drop_table('exam_violations')
    # ### end Alembic commands ###
