"""added exam_archived value for examaction enum

Revision ID: cc91c44339b5
Revises: fb6ee59dd258
Create Date: 2026-08-12 22:08:47.980472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc91c44339b5'
down_revision: Union[str, Sequence[str], None] = 'fb6ee59dd258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
