"""added archived value for exam_status enum

Revision ID: fb6ee59dd258
Revises: 9ce3554d958d
Create Date: 2026-08-12 20:56:49.402549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6ee59dd258'
down_revision: Union[str, Sequence[str], None] = '9ce3554d958d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE examstatus ADD VALUE IF NOT EXISTS 'ARCHIVED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
