"""Create Item Bank Tables

Revision ID: 66136c0f5d8f
Revises: 
Create Date: 2026-05-14 13:50:50.455077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '66136c0f5d8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='subjectstatus'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.create_index(op.f('ix_subjects_org_id'), 'subjects', ['org_id'], unique=False)
    op.create_table('bulk_upload_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_upload_logs_org_id'), 'bulk_upload_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_bulk_upload_logs_subject_id'), 'bulk_upload_logs', ['subject_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('item_type', sa.Enum('MCQ_SINGLE', 'MCQ_MULTI', 'SHORT_ANSWER', 'NUMERIC', 'TRUE_FALSE', name='itemtype'), nullable=False),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('correct_answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('negative_marks', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='itemdifficulty'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='itemstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'EXCEL_UPLOAD', 'AI_GENERATED', 'IMPORTED', name='itemsource'), nullable=False),
    sa.Column('bulk_upload_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_bulk_upload_id'), 'items', ['bulk_upload_id'], unique=False)
    op.create_index(op.f('ix_items_created_by'), 'items', ['created_by'], unique=False)
    op.create_index(op.f('ix_items_difficulty'), 'items', ['difficulty'], unique=False)
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    op.create_index(op.f('ix_items_org_id'), 'items', ['org_id'], unique=False)
    op.create_index(op.f('ix_items_source'), 'items', ['source'], unique=False)
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    op.create_index(op.f('ix_items_subject_id'), 'items', ['subject_id'], unique=False)
    op.create_table('subject_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_assignments_assigned_to'), 'subject_assignments', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_subject_assignments_org_id'), 'subject_assignments', ['org_id'], unique=False)
    op.create_index(op.f('ix_subject_assignments_subject_id'), 'subject_assignments', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_assignments_subject_id'), table_name='subject_assignments')
    op.drop_index(op.f('ix_subject_assignments_org_id'), table_name='subject_assignments')
    op.drop_index(op.f('ix_subject_assignments_assigned_to'), table_name='subject_assignments')
    op.drop_table('subject_assignments')
    op.drop_index(op.f('ix_items_subject_id'), table_name='items')
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index(op.f('ix_items_source'), table_name='items')
    op.drop_index(op.f('ix_items_org_id'), table_name='items')
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.drop_index(op.f('ix_items_difficulty'), table_name='items')
    op.drop_index(op.f('ix_items_created_by'), table_name='items')
    op.drop_index(op.f('ix_items_bulk_upload_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_bulk_upload_logs_subject_id'), table_name='bulk_upload_logs')
    op.drop_index(op.f('ix_bulk_upload_logs_org_id'), table_name='bulk_upload_logs')
    op.drop_table('bulk_upload_logs')
    op.drop_index(op.f('ix_subjects_org_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
