"""renewed with enum types field update

Revision ID: 00f8a5c82d71
Revises: 
Create Date: 2026-06-03 08:59:26.940988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00f8a5c82d71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'GRADUATED', 'ARCHIVED', name='cohortstatus'), nullable=False),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('graduated_at', sa.DateTime(), nullable=True),
    sa.Column('graduated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohorts_name'), 'cohorts', ['name'], unique=False)
    op.create_index(op.f('ix_cohorts_org_id'), 'cohorts', ['org_id'], unique=False)
    op.create_index(op.f('ix_cohorts_status'), 'cohorts', ['status'], unique=False)
    op.create_table('platform_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='platformplanstatus'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('max_staff', sa.Integer(), nullable=True),
    sa.Column('max_exams', sa.Integer(), nullable=True),
    sa.Column('max_cohorts', sa.Integer(), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('paystack_plan_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_plans_interval'), 'platform_plans', ['interval'], unique=False)
    op.create_index(op.f('ix_platform_plans_name'), 'platform_plans', ['name'], unique=False)
    op.create_index(op.f('ix_platform_plans_status'), 'platform_plans', ['status'], unique=False)
    op.create_table('users',
    sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('othername', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.Enum('EMAIL_OTP', 'ACCESS_CODE', name='verificationmethod'), nullable=True),
    sa.Column('is_first_login', sa.Boolean(), nullable=False),
    sa.Column('access_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('favorite_question', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('favorite_answer_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_access_code'), 'users', ['access_code'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_table('cohort_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_members_cohort_id'), 'cohort_members', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_cohort_members_org_id'), 'cohort_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_cohort_members_student_id'), 'cohort_members', ['student_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_type', sa.Enum('SCHOOL', 'UNIVERSITY', 'CORPORATE', 'EXAM_BODY', 'RECRUITMENT', 'CERTIFICATION', 'GOVERNMENT', 'OTHER', name='organizationtype'), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'PUBLIC', name='organizationvisibility'), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('allow_self_subscription', sa.Boolean(), nullable=False),
    sa.Column('require_subscription_approval', sa.Boolean(), nullable=False),
    sa.Column('exam_body_trial_days', sa.Integer(), nullable=False),
    sa.Column('subscription_plan', sa.Enum('FREE', 'PAID', name='subscriptionplan'), nullable=False),
    sa.Column('subscription_price', sa.Float(), nullable=True),
    sa.Column('subscription_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscription_duration_days', sa.Integer(), nullable=True),
    sa.Column('paystack_plan_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=True)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_owner_user_id'), 'organizations', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_organizations_phone'), 'organizations', ['phone'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organizations_updated_at'), 'organizations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_organizations_visibility'), 'organizations', ['visibility'], unique=False)
    op.create_table('bulk_org_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('exam_body_org_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paystack_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paystack_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'REFUNDED', name='subscriptionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_body_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_org_subscriptions_exam_body_org_id'), 'bulk_org_subscriptions', ['exam_body_org_id'], unique=False)
    op.create_index(op.f('ix_bulk_org_subscriptions_org_id'), 'bulk_org_subscriptions', ['org_id'], unique=False)
    op.create_index(op.f('ix_bulk_org_subscriptions_paystack_reference'), 'bulk_org_subscriptions', ['paystack_reference'], unique=True)
    op.create_index(op.f('ix_bulk_org_subscriptions_status'), 'bulk_org_subscriptions', ['status'], unique=False)
    op.create_table('exam_body_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('exam_body_org_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'PAID', name='subscriptionplan'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'REFUNDED', name='subscriptionstatus'), nullable=False),
    sa.Column('subscribed_by', sa.Enum('SELF', 'ORGANIZATION', name='subscribedby'), nullable=False),
    sa.Column('paystack_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paystack_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_body_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_body_subscriptions_exam_body_org_id'), 'exam_body_subscriptions', ['exam_body_org_id'], unique=False)
    op.create_index(op.f('ix_exam_body_subscriptions_org_id'), 'exam_body_subscriptions', ['org_id'], unique=False)
    op.create_index(op.f('ix_exam_body_subscriptions_paystack_reference'), 'exam_body_subscriptions', ['paystack_reference'], unique=True)
    op.create_index(op.f('ix_exam_body_subscriptions_status'), 'exam_body_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_exam_body_subscriptions_student_id'), 'exam_body_subscriptions', ['student_id'], unique=False)
    op.create_table('org_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'TEACHER', 'STUDENT', 'SUPERVISOR', 'STAFF', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'ARCHIVED', 'REMOVED', name='membershipstatus'), nullable=False),
    sa.Column('join_type', sa.Enum('INVITED', 'SELF_JOINED', 'AUTO_ADDED', name='membershipjointype'), nullable=False),
    sa.Column('institution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verification_method', sa.Enum('EMAIL_OTP', 'ACCESS_CODE', name='verificationmethod'), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('archived_by', sa.Uuid(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_memberships_join_type'), 'org_memberships', ['join_type'], unique=False)
    op.create_index(op.f('ix_org_memberships_org_id'), 'org_memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_memberships_status'), 'org_memberships', ['status'], unique=False)
    op.create_index(op.f('ix_org_memberships_user_id'), 'org_memberships', ['user_id'], unique=False)
    op.create_table('org_platform_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'PAST_DUE', name='orgsubscriptionstatus'), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('max_staff', sa.Integer(), nullable=True),
    sa.Column('paystack_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paystack_subscription_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paystack_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['platform_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_platform_subscriptions_org_id'), 'org_platform_subscriptions', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_platform_subscriptions_paystack_reference'), 'org_platform_subscriptions', ['paystack_reference'], unique=False)
    op.create_index(op.f('ix_org_platform_subscriptions_status'), 'org_platform_subscriptions', ['status'], unique=False)
    op.create_table('organization_settings',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()).with_variant(postgresql.JSON(astext_type=sa.Text()), 'sqlite'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_settings_org_id'), 'organization_settings', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_settings_org_id'), table_name='organization_settings')
    op.drop_table('organization_settings')
    op.drop_index(op.f('ix_org_platform_subscriptions_status'), table_name='org_platform_subscriptions')
    op.drop_index(op.f('ix_org_platform_subscriptions_paystack_reference'), table_name='org_platform_subscriptions')
    op.drop_index(op.f('ix_org_platform_subscriptions_org_id'), table_name='org_platform_subscriptions')
    op.drop_table('org_platform_subscriptions')
    op.drop_index(op.f('ix_org_memberships_user_id'), table_name='org_memberships')
    op.drop_index(op.f('ix_org_memberships_status'), table_name='org_memberships')
    op.drop_index(op.f('ix_org_memberships_org_id'), table_name='org_memberships')
    op.drop_index(op.f('ix_org_memberships_join_type'), table_name='org_memberships')
    op.drop_table('org_memberships')
    op.drop_index(op.f('ix_exam_body_subscriptions_student_id'), table_name='exam_body_subscriptions')
    op.drop_index(op.f('ix_exam_body_subscriptions_status'), table_name='exam_body_subscriptions')
    op.drop_index(op.f('ix_exam_body_subscriptions_paystack_reference'), table_name='exam_body_subscriptions')
    op.drop_index(op.f('ix_exam_body_subscriptions_org_id'), table_name='exam_body_subscriptions')
    op.drop_index(op.f('ix_exam_body_subscriptions_exam_body_org_id'), table_name='exam_body_subscriptions')
    op.drop_table('exam_body_subscriptions')
    op.drop_index(op.f('ix_bulk_org_subscriptions_status'), table_name='bulk_org_subscriptions')
    op.drop_index(op.f('ix_bulk_org_subscriptions_paystack_reference'), table_name='bulk_org_subscriptions')
    op.drop_index(op.f('ix_bulk_org_subscriptions_org_id'), table_name='bulk_org_subscriptions')
    op.drop_index(op.f('ix_bulk_org_subscriptions_exam_body_org_id'), table_name='bulk_org_subscriptions')
    op.drop_table('bulk_org_subscriptions')
    op.drop_index(op.f('ix_organizations_visibility'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_updated_at'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_phone'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_owner_user_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_cohort_members_student_id'), table_name='cohort_members')
    op.drop_index(op.f('ix_cohort_members_org_id'), table_name='cohort_members')
    op.drop_index(op.f('ix_cohort_members_cohort_id'), table_name='cohort_members')
    op.drop_table('cohort_members')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_access_code'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_platform_plans_status'), table_name='platform_plans')
    op.drop_index(op.f('ix_platform_plans_name'), table_name='platform_plans')
    op.drop_index(op.f('ix_platform_plans_interval'), table_name='platform_plans')
    op.drop_table('platform_plans')
    op.drop_index(op.f('ix_cohorts_status'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_org_id'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_name'), table_name='cohorts')
    op.drop_table('cohorts')
    # ### end Alembic commands ###
