"""Teacher Cohort Assignment

Revision ID: 18c10f114832
Revises: 00f8a5c82d71
Create Date: 2026-06-30 17:52:14.485138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18c10f114832'
down_revision: Union[str, Sequence[str], None] = '00f8a5c82d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_cohort_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_cohort_assignments_cohort_id'), 'teacher_cohort_assignments', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_teacher_cohort_assignments_org_id'), 'teacher_cohort_assignments', ['org_id'], unique=False)
    op.create_index(op.f('ix_teacher_cohort_assignments_teacher_id'), 'teacher_cohort_assignments', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_cohort_assignments_teacher_id'), table_name='teacher_cohort_assignments')
    op.drop_index(op.f('ix_teacher_cohort_assignments_org_id'), table_name='teacher_cohort_assignments')
    op.drop_index(op.f('ix_teacher_cohort_assignments_cohort_id'), table_name='teacher_cohort_assignments')
    op.drop_table('teacher_cohort_assignments')
    # ### end Alembic commands ###
