"""added constraints

Revision ID: 994bd6191824
Revises: 18c10f114832
Create Date: 2026-08-12 13:30:20.619652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '994bd6191824'
down_revision: Union[str, Sequence[str], None] = '18c10f114832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cohort_member', 'cohort_members', ['cohort_id', 'student_id', 'org_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cohort_member', 'cohort_members', type_='unique')
    # ### end Alembic commands ###
