"""add new fields

Revision ID: e3a43df2281e
Revises: af778ad43a09
Create Date: 2026-05-05 17:49:59.779028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3a43df2281e'
down_revision: Union[str, Sequence[str], None] = 'af778ad43a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=True)
    op.add_column('users', sa.Column('is_first_login', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('institution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('access_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('favorite_question', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('favorite_answer_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'TEACHER', 'STUDENT', 'SUPERVISOR', name='userrole'),
               nullable=True)
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_access_code'), 'users', ['access_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_access_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'TEACHER', 'STUDENT', 'SUPERVISOR', name='userrole'),
               nullable=False)
    op.alter_column('users', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'password')
    op.drop_column('users', 'favorite_answer_hash')
    op.drop_column('users', 'favorite_question')
    op.drop_column('users', 'access_code')
    op.drop_column('users', 'institution_id')
    op.drop_column('users', 'is_first_login')
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=False)
    # ### end Alembic commands ###
