"""Made Access Code Unique

Revision ID: fa2bb30ebc81
Revises: e3a43df2281e
Create Date: 2026-05-11 15:41:34.688238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa2bb30ebc81'
down_revision: Union[str, Sequence[str], None] = 'e3a43df2281e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_access_code'), table_name='users')
    op.create_index(op.f('ix_users_access_code'), 'users', ['access_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_access_code'), table_name='users')
    op.create_index(op.f('ix_users_access_code'), 'users', ['access_code'], unique=False)
    # ### end Alembic commands ###
